
name: Modified Maven verify
jobs:
  mvn_verify:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-mvn_verify.csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/Mybatis-PageHelper/Mybatis-PageHelper', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - uses: actions/checkout@v3
    - run: touch optcd-3.txt
    - name: Set up Maven Central Repository
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: adopt
    - run: touch optcd-4.txt
    - name: Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots -P dev verify -Dsurefire.useFile=false
        -DdisableXmlReport=true
    - run: touch optcd-5.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-mvn_verify
        path: /home/runner/inotifywait-log-mvn_verify.csv
    name: mvn_verify
'on':
- push
- workflow_dispatch
